name: Build Android APK

on:
  # 手动触发
  workflow_dispatch:
    inputs:
      build_type:
        description: '构建类型'
        required: true
        default: 'debug'
        type: choice
        options:
        - debug
        - release
  
  # 推送到main分支时自动构建
  push:
    branches: [ main, master ]
    paths:
      - 'lib/**'
      - 'android/**'
      - 'pubspec.yaml'
  
  # Pull Request时构建
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
    
    - name: 设置Java环境
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: 设置Flutter环境
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'
        cache: true
    
    - name: 获取Flutter依赖
      run: flutter pub get
    
    - name: 检查Flutter环境
      run: flutter doctor -v
    
    - name: 清理构建缓存
      run: flutter clean
    
    - name: 构建APK (Debug)
      if: ${{ github.event.inputs.build_type == 'debug' || github.event.inputs.build_type == '' }}
      run: |
        flutter build apk --debug --split-per-abi
        flutter build apk --debug --target-platform android-arm64
    
    - name: 构建APK (Release)
      if: ${{ github.event.inputs.build_type == 'release' }}
      run: |
        flutter build apk --release --split-per-abi
        flutter build apk --release --target-platform android-arm64
    
    - name: 重命名APK文件
      run: |
        mkdir -p output
        BUILD_TYPE="${{ github.event.inputs.build_type || 'debug' }}"
        TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
        
        if [ "$BUILD_TYPE" = "release" ]; then
          # Release版本
          cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk output/ghosten-player-arm64-release-${TIMESTAMP}.apk
          cp build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk output/ghosten-player-arm32-release-${TIMESTAMP}.apk || true
          cp build/app/outputs/flutter-apk/app-x86_64-release.apk output/ghosten-player-x64-release-${TIMESTAMP}.apk || true
          cp build/app/outputs/flutter-apk/app-release.apk output/ghosten-player-universal-release-${TIMESTAMP}.apk
        else
          # Debug版本
          cp build/app/outputs/flutter-apk/app-arm64-v8a-debug.apk output/ghosten-player-arm64-debug-${TIMESTAMP}.apk
          cp build/app/outputs/flutter-apk/app-armeabi-v7a-debug.apk output/ghosten-player-arm32-debug-${TIMESTAMP}.apk || true
          cp build/app/outputs/flutter-apk/app-x86_64-debug.apk output/ghosten-player-x64-debug-${TIMESTAMP}.apk || true
          cp build/app/outputs/flutter-apk/app-debug.apk output/ghosten-player-universal-debug-${TIMESTAMP}.apk
        fi
    
    - name: 上传APK文件
      uses: actions/upload-artifact@v4
      with:
        name: android-apk-${{ github.event.inputs.build_type || 'debug' }}-${{ github.run_number }}
        path: output/*.apk
        retention-days: 30
    
    - name: 显示构建信息
      run: |
        echo "构建完成！"
        echo "构建类型: ${{ github.event.inputs.build_type || 'debug' }}"
        echo "提交SHA: ${{ github.sha }}"
        echo "运行编号: ${{ github.run_number }}"
        ls -la output/
